### ISSUE TITLE
关于NewRoundRobinBalancer的疑问

### ISSUE THREAD

**Issue by go-roc** [rsocket/rsocket-go#100]
如果我在连接客户端的时候指定了n个server，在线上跑的时候，突然一个server挂掉了，是怎么处理的呢--NewRoundRobinBalancer。你有wechat或者别的联系方式吗？群也行，我提的问题，觉得发在issues这里不太好.....另外，我发现我用etcd做服务发现是多余的。

**Comment by jjeffcaii** [comment]
可以加我微信
![WechatIMG64](https://user-images.githubusercontent.com/1284892/107171233-3d3d4500-69fd-11eb-9881-858516ec8820.jpeg)
