### ISSUE TITLE
Let user specify a Proxy func for NewWebsocketClientTransport

### ISSUE THREAD

**Issue by ronakg** [rsocket/rsocket-go#103]
## Motivation

For the `NewWebsocketClientTransport`, the proxy function is hardcoded to `http.ProxyFromEnvironment`. This is not ideal for processes where multiple Proxy settings are required.  Java SDK allows the user to pass in an `httpClient`, which can have its own Proxy configuration.

## Desired solution

When invoking `NewWebsocketClientTransport`, let the user provide a Proxy function that can be passed to `websocket.Dialer`. The function signature is a de-facto standard, it's used by `http.Transport` as well. 

## Considered alternatives

None.

## Additional context

The change is very straight-forward and provides more flexibility to the user of rsocket-go.

Proposed changes in my fork: https://github.com/ronakg/rsocket-go/commit/5133e493d058e8a7e95620bb6f3b1d3f8b173a9c. I can raise the PR once we have discussed the solution in this issue.

**Comment by jjeffcaii** [comment]
Thanks for reporting!
It makes sense, great if you raise the PR. I'll be happy to merge it. 😄

**Comment by jjeffcaii** [comment]
The v0.8.1 released with this new feature. 🎉 🎉 🎉 

Thanks for your hard work!
