### ISSUE TITLE
When calling request-channel from javascript SDK, program got a panic with "cannot cancel".

### ISSUE THREAD

**Issue by go-roc** [rsocket/rsocket-go#119]
![9652bd519d9b56225e4ef621e926855](https://user-images.githubusercontent.com/76894028/154056764-2d85e05d-adb5-4aaa-9b08-5eb85a1a8bc0.png)

**Comment by jjeffcaii** [comment]
@go-roc Pls try v0.8.7.

**Comment by jjeffcaii** [comment]
@go-roc try v0.8.8, pls

**Comment by jjeffcaii** [comment]
fixed
