### ISSUE TITLE
Competing implementations

### ISSUE THREAD

**Issue by fiorix** [rsocket/rsocket-go#4]
Hello folks :)

I'm afraid we may end up with competing implementations. We have a (semi) spec compliant rsocket protocol implementation for Go, which we want to use in Thrift.

A couple weeks ago I started socializing the idea of open sourcing it in this repository and started setting up the automation to sync our codebase over here. But earlier this week I noticed you started landing your implementation and was surprised.

I don't know who's governing the 'rsocket' entity here on GitHub, but we should probably talk.

Is there a slack or irc where you hang out? Please let me know.

**Comment by jjeffcaii** [comment]
Hi,
https://rsocket.slack.com/
I just invite you.

**Comment by fiorix** [comment]
Cool, thanks
