### ISSUE TITLE
Checksum mismatch for go 1.13 for ants Dependency

### ISSUE THREAD

**Issue by Pinedo11** [rsocket/rsocket-go#40]
Seems that there is some problem with the checksum validation of the github.com/panjf2000/ants dependency.

Output of `go get -u github.com/rsocket/rsocket-go`:

```
go: finding github.com/rsocket/rsocket-go v0.3.2
go: downloading github.com/rsocket/rsocket-go v0.3.2
go: extracting github.com/rsocket/rsocket-go v0.3.2
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/jjeffcaii/reactor-go v0.0.16
go: extracting github.com/jjeffcaii/reactor-go v0.0.16
go: downloading github.com/panjf2000/ants v1.2.0
go: extracting github.com/pkg/errors v0.8.1
verifying github.com/panjf2000/ants@v1.2.0: checksum mismatch
        downloaded: h1:Ufw4aDz9RqH1RVblx2W9L9Uv5vSX5apbX5+peR7LQ5k=
        sum.golang.org: h1:pMQ1/XpSgnWx3ro4y1xr/uA3jXUsTuAaU3Dm0JjwggE=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by jjeffcaii** [comment]
Thanks for reporting this issue! 
It seems that there are similar problems here: https://github.com/panjf2000/ants/issues/49

**Comment by Pinedo11** [comment]
Yeah, but the suggested workaround  on that issue doesn't work for me

**Comment by jjeffcaii** [comment]
I did a test in go 1.13. Unfortunately, there is no recurring problem. https://asciinema.org/a/EfcpIz2uIJV89wZb7xjPrdkG7

I am so confused how the problem happened. 囧rz
Have you changed GOPROXY or GOSUMDB? Or try release v0.4.0?

**Comment by Pinedo11** [comment]
My bad I was trying to install the dependency from the integrated terminal of IntelliJ and for some reason the IDE sets the GOPROXY  to "direct" into env variables, problem solved, thanks for the support!
