### ISSUE TITLE
typo in socket.go

### ISSUE THREAD

**Issue by alibas** [rsocket/rsocket-go#47]
Hi,
In line 91 in socket.go: p.MP should be p.FF I think

**Comment by OlegDokuka** [comment]
Hey @alibas!

Thanks for reporting that! Feel free o create a PR and contribute to the project that way 😀

Cheers,
Oleh

**Comment by alibas** [comment]
ok just thought it wasn't a big deal for pr :D

**Comment by OlegDokuka** [comment]
Well!

It is a good start!

**Comment by OlegDokuka** [comment]
Merged!
Thanks for your contribution and welcome!

Cheers,
Oleh

**Comment by jjeffcaii** [comment]
Thanks for your contribution! 👍

**Comment by alibas** [comment]
My pleasure
