### ISSUE TITLE
Roadmap and the future? 

### ISSUE THREAD

**Issue by Codebreaker101** [rsocket/rsocket-go#50]
I've just heard of rsocket as an alternative to gRPC and I'm wondering what is the future of `rsocket-go`.

`rsocket-go` has not seen as much love as other implementation, notably c++ and especially java and has sparse commits this year. Is it because the protocol is fully implemented? 

All but one `TODO` has been completed. Does that mean that we could get `v1` soon, or at least RC? If there are more to do, could this be updated to include what else needs to be done so that the community can engage better.

**Comment by jjeffcaii** [comment]
Thank you for your attention! 😀 
Most of features has been completely covered, but It lacks sufficient testing.
I don't have enough time to maintain this project, so it is slow for development. Maybe we can release v1 in this autumn if everything goes well.
