### ISSUE TITLE
rpc pool

### ISSUE THREAD

**Issue by go-roc** [rsocket/rsocket-go#99]
同一台机器使用多个客户端连接池，性能急剧下降。
//1.2021-01-24
//cpu: i9 2.3hz
//rom:16G
//direct use origin rsocket
//-------------tps------------ 153754
//-------------tps------------ 154480
//-------------tps------------ 153816
//-------------tps------------ 159207
//-------------tps------------ 156221

使用pool建立多个连接之后
//-------------tps------------ 67442
//-------------tps------------ 68952
//-------------tps------------ 68716
//-------------tps------------ 70428
//-------------tps------------ 67465
//-------------tps------------ 67358

**Comment by jjeffcaii** [comment]
谢谢反馈~ 是指用`sync.Pool`做连接池，池中的每个connection连接到不同的server，是这样理解么？

**Comment by go-roc** [comment]
> 谢谢反馈~ 是指用`sync.Pool`做连接池，池中的每个connection连接到不同的server，是这样理解么？

差不多，就是一台客户端，初始化就建立10，100个连接这样，然后轮询请求服务端

**Comment by jjeffcaii** [comment]
能方便贴一些样例代码么？我这边调试排查下。另外其实rsocket本身是多路复用的，一般一个server一个连接就可以了，不需要做pool。

**Comment by go-roc** [comment]
https://github.com/go-roc/roc/_example/helloworld/api/bench/main.go commit e310a3c4ced7cc55d48ccd29220eeeac16c93b1a    ---lazypool分支,....grpc也是多路复用，但是grpc在客户端100，并发1000的时候能达到20万/s,rscoket单实例requestresponse是16万/s，单机客户端越多，rscoket并发越低,稍等我专门填一下测试代码

**Comment by jjeffcaii** [comment]
晚点我调试下，谢谢！

**Comment by jjeffcaii** [comment]
@go-roc 我做了一些调整，你试试看有没有提升。

```go
package main

import (
	"context"
	"fmt"
	"log"
	"sync/atomic"
	"time"

	"github.com/jjeffcaii/reactor-go/scheduler"
	"github.com/rsocket/rsocket-go"
	"github.com/rsocket/rsocket-go/core/transport"
	"github.com/rsocket/rsocket-go/payload"
	"github.com/rsocket/rsocket-go/rx"
)

var tp transport.ClientTransporter

func init() {
	tp = rsocket.TCPClient().SetHostAndPort("127.0.0.1", 7878).Build()
}

func main() {
	const (
		parallel = 100
		round    = 100
		amount   = 100000
	)
	var clients []rsocket.Client
	for i := 0; i < parallel; i++ {
		client, err := createClient()
		if err != nil {
			return
		}
		clients = append(clients, client)
	}
	defer func() {
		for _, c := range clients {
			_ = c.Close()
		}
	}()
	if len(clients) == 0 {
		return
	}
	time.Sleep(time.Second * 1)

	var tps int64
	var next uint64

	done := make(chan struct{})

	cnt := int64(round * amount)

	// 创建订阅
	sub := rx.NewSubscriber(
		rx.OnComplete(func() {
			atomic.AddInt64(&tps, 1)
			if atomic.AddInt64(&cnt, -1) < 1 {
				close(done)
			}
		}),
		rx.OnError(func(e error) {
			if atomic.AddInt64(&cnt, -1) < 1 {
				close(done)
			}
		}),
	)

	for range [round]struct{}{} {
		go func(c rsocket.Client) {
			for range [amount]struct{}{} {
				// 这里尽量避免用Block, 直接订阅response即可, 订阅默认就是异步的, 所以不需要额外创建协程去执行。
				//
				// 原本的Block会导致一次Copy, 如果场景考虑性能又要需要阻塞获取response, 可以使用BlockUnsafe:
				//
				// go func() {
				// 	  res, closer, err := c.RequestResponse(payload.NewString("hello", "")).BlockUnsafe(context.Background())
				// 	  if err != nil {
				// 	  	  return
				// 	  }
				//    // 这里需要确保最后调用closer, 此方法会将response所占用的资源释放(response的payload为了减少GC是pooled的)。
				// 	  defer closer()
				// 	  log.Println("response:", res)
				// }()
				//
				c.RequestResponse(payload.NewString("hello", "")).SubscribeWith(context.Background(), sub)
			}
		}(clients[(int(atomic.AddUint64(&next, 1))-1)%len(clients)])
	}

	for {
		select {
		case <-done:
			return
		case <-time.After(time.Second * 1):
			fmt.Println("-----------------------tps-------------------", atomic.LoadInt64(&tps))
			atomic.SwapInt64(&tps, 0)
		}
	}
}

func createClient() (rsocket.Client, error) {
	return rsocket.Connect().
		Scheduler(scheduler.Elastic(), nil). // 这里设置发送请求时调度器为动态无界协程池
		OnClose(func(err error) {
			log.Println("*** disconnected ***")
		}).
		SetupPayload(payload.NewString("你好", "世界")).
		Transport(tp).
		Start(context.Background())
}


```

**Comment by go-roc** [comment]
嗯，这个明白，但是我想在这里实现的是“请求-响应”，这样的模式。如果用NewSubscriber，请求端无法感知是"哪一次"。
这是使用blockUnsafe的多客户端模式下，达到预期了，感谢。这个issue可以关闭了。
-----------------------tps-------------------144181------errCount=0
-----------------------tps-------------------130388------errCount=0
-----------------------tps-------------------131925------errCount=0
-----------------------tps-------------------130454------errCount=0
-----------------------tps-------------------128414------errCount=0
-----------------------tps-------------------126628------errCount=0
-----------------------tps-------------------141378------errCount=0
-----------------------tps-------------------133409------errCount=0

**Comment by jjeffcaii** [comment]
顺便提一下，这里如果需要“感知”，Subscribe的时候每次创建新的subscriber即可， 比如:
```go
c.RequestResponse(payload.NewString("hello", "")).Subscribe(ctx, rx.OnNext(...), rx.OnError(...))
```

**Comment by go-roc** [comment]
好的，感谢

**Comment by jjeffcaii** [comment]
客气~ 有问题随时沟通~ 😀
